### PR TITLE
Mirgrate to akka typed 2.5.7

### PR DESCRIPTION
**Pull request by Jentsch**
I updated the source code to work with akka-typed 2.5.7.

Since the blog post uses the 2.5.7-M1 API, may a short notice about the changes (or even a new blog post) would be helpful. Or just discard this pull request to avoid confusion. I'm not sure how to handle the relation between blog post and this repository.

Kind regards,
Jentsch

### CODE REVIEW

**Comment by raboof** [comment]
Perhaps we should even just retroactively update the blogpost to the new API? (it's at https://github.com/akka/akka.github.com)

**Comment by patriknw** [comment]
Excellent, thanks a lot @Jentsch 

Could you also create a PR for the blog posts? Code is copied there. https://github.com/akka/akka.github.com/tree/master/blog/_posts

I want to keep these examples up to date with latest, and also update the blog posts, since we don't have much other documentation. I don't think we need writing migration guides yet. Too many things are still moving. PRs like this is a good guide for others though.

**Comment by Jentsch** [comment]
Yes, give me a little bit time. Hopefully around Monday an PR to update the blog post should arrive.

**Comment by patriknw** [comment]
that's great, thanks

**Pull request merged**
